channels:
- conda-forge
- bioconda

dependencies:
- python==3.12
- snakemake==8.4
- r-base==4.3.2
- openjdk==21.0.2
- r-rjava==1.0_11
- bioconductor-biostrings==2.70.1
- bioconductor-biocparallel==1.36.0
- bioconductor-cardinal==3.4.3
- bioconductor-cleaver==1.40.0
- bioconductor-rdisop==1.62.0
- bioconductor-keggrest==1.42.0
- bioconductor-multtest==2.58.0
- bioconductor-chemminer==3.54.0
- r-tidyverse==2.0.0
- r-protviz==0.7.7
- r-rcdk==3.8.1
- r-orgmassspecr==0.5.3
- r-rcdklibs==2.8
- r-scales==1.2.1
- r-pacman==0.5.1
- r-pryr==0.1.6
- r-pls==2.8_3
- r-magick==2.8.2
- r-reticulate==1.34.0
- r-doparallel==1.0.17
- r-foreach==1.5.2
- r-egg==0.4.5
- r-spdep==1.3_1
- r-zoo==1.8_12
- r-envipat==2.6
- r-rgl==1.2.8
- r-xml==3.99_0.16.1
- r-reshape2==1.4.4
- r-oner==2.2
- r-gridextra==2.3
- r-biocmanager==1.30.22
- r-units==0.8_5
- r-sf==1.0_15
- r-devtools==2.4.5
- r-colortools==0.1.5
- r-plotly==4.10.4